meta_product_name: "Silverhelp"
meta_title: "Silverhelp - Everyday life made easy"
meta_description: "Find help for any of your daily tasks from friendly local volunteers"
meta_image: "metaimage.jpeg" # should exist in `app/assets/images/`
